List<Map> NavList = [
  {
    "title":"酒店",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/hotel.png"
  },
  {
    "title":"机票",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/flight.png"
  },
  {
    "title":"度假",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/hotel.png"
  },
  {
    "title":"火车票",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/hotel.png"
  },
  {
    "title":"景点门票",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/hotel.png"
  }
];